spring.flyway.placeholders.seed.enabled=true

# kafka (dev)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# keep event payload portable between services
spring.kafka.properties.spring.json.add.type.headers=false

# app events
app.events.topic=winecellar.events
