-- =========================
-- Winery table
-- =========================
CREATE TABLE winery (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        country VARCHAR(255) NOT NULL,
                        version BIGINT NOT NULL
);

-- Matches your entity constraint name (optional but clean)
ALTER TABLE winery
    ADD CONSTRAINT uk_winery_name_country UNIQUE (name, country);

-- =========================
-- Wine table
-- =========================
CREATE TABLE wine (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      winery_id BIGINT NOT NULL,
                      country VARCHAR(255) NOT NULL,
                      wine_year INT NOT NULL,
                      price DECIMAL(19,2) NOT NULL,
                      version BIGINT NOT NULL,

                      CONSTRAINT fk_wine_winery
                          FOREIGN KEY (winery_id) REFERENCES winery(id),

                      CONSTRAINT uk_wine_name_year_winery
                          UNIQUE (name, wine_year, winery_id)
);

CREATE INDEX idx_wine_winery_id ON wine (winery_id);
